USE Inventory_System;

LOAD DATA LOCAL INFILE "C:/inventorySystem/databaseDocs/Category.csv"
INTO TABLE Category
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n';


LOAD DATA LOCAL INFILE "C:/inventorySystem/databaseDocs/ProductData.csv"
INTO TABLE Product
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE "C:/inventorySystem/databaseDocs/Nutrition.csv"
INTO TABLE Nutrition
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n';


LOAD DATA LOCAL INFILE "C:/inventorySystem/databaseDocs/serving_size.csv"
INTO TABLE Serving_size
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE "C:/inventorySystem/databaseDocs/inventoryListData.csv"
INTO TABLE inventory_list
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n';

