package PerfectPantryApp;


import java.awt.event.*;
import java.sql.SQLException;

import javax.swing.*;
import javax.swing.table.*;




/**
 * This class creates the GUI for the Perfect Pantry application.
 * @author Hira Waqas, Josh Gugel
 */
public class PerfectPantryGUI extends JFrame {

    private JDBC jdbc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addInventoryButton;
    private JPanel categoriesPanel;
    private JLabel filterLabel;
    private JCheckBox produceCheckBox;
    private JPanel inventoryLeftPanel;
    private JPanel inventoryRightPanel;
    private JSplitPane inventorySplitPane;
    private JTabbedPane inventoryTabPane;
    private JTable inventoryTable;
    private JScrollPane jScrollPane1;
    private JComboBox<String> sortingComboBox;
    private JLabel sortingLabel;
    private JPanel sortingPanel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form PerfectPantryGUI
     */
    public PerfectPantryGUI() {
        jdbc = new JDBC();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryTabPane = new JTabbedPane();
        inventorySplitPane = new JSplitPane();
        inventoryLeftPanel = new JPanel();
        addInventoryButton = new JButton();
        categoriesPanel = new JPanel();
        bakingCB = new javax.swing.JCheckBox();
        beveragesCB = new javax.swing.JCheckBox();
        breadsBakeryCB = new javax.swing.JCheckBox();
        dairyRefCB = new javax.swing.JCheckBox();
        householdSCB = new javax.swing.JCheckBox();
        meatsPoultryCB = new javax.swing.JCheckBox();
        miscellaneousCB = new javax.swing.JCheckBox();
        pantryCB = new javax.swing.JCheckBox();
        inventoryRightPanel = new JPanel();
        sortingPanel = new JPanel();
        filterLabel = new JLabel();
        sortingLabel = new JLabel();
        sortingComboBox = new JComboBox<>();
        jScrollPane1 = new JScrollPane();
        inventoryTable = new JTable();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfect Pantry");

        addInventoryButton.setText("Add Inventory");
        addInventoryButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addInventoryButtonActionPerformed(evt);
            }
        });
        categoriesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Categories"));

        bakingCB.setText("Baking, Herbs, and Spices");
        bakingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        beveragesCB.setText("Beverages");
        beveragesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        breadsBakeryCB.setText("Breads and Bakery");
        breadsBakeryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        dairyRefCB.setText("Dairy and Refrigerated");
        dairyRefCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        householdSCB.setText("Household Supplies");
        householdSCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        meatsPoultryCB.setText("Meats and Poultry");
        meatsPoultryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        miscellaneousCB.setText("Miscellaneous");
        miscellaneousCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesSelectionActionPerformed(evt);
            }
        });

        pantryCB.setText("Pantry");
        pantryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               categoriesSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
        categoriesPanel.setLayout(categoriesPanelLayout);
        categoriesPanelLayout.setHorizontalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bakingCB))
                    .addGroup(categoriesPanelLayout.createSequentialGroup()
                        .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miscellaneousCB)
                            .addComponent(pantryCB)
                            .addComponent(beveragesCB)
                            .addComponent(breadsBakeryCB)
                            .addComponent(dairyRefCB)
                            .addComponent(householdSCB)
                            .addComponent(meatsPoultryCB))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        categoriesPanelLayout.setVerticalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bakingCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beveragesCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breadsBakeryCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dairyRefCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(householdSCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meatsPoultryCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miscellaneousCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantryCB))
        );

        GroupLayout inventoryLeftPanelLayout = new GroupLayout(inventoryLeftPanel);
        inventoryLeftPanel.setLayout(inventoryLeftPanelLayout);
        inventoryLeftPanelLayout.setHorizontalGroup(
            inventoryLeftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(inventoryLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryLeftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoriesPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addInventoryButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inventoryLeftPanelLayout.setVerticalGroup(
            inventoryLeftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(inventoryLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addInventoryButton)
                .addGap(18, 18, 18)
                .addComponent(categoriesPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        inventorySplitPane.setLeftComponent(inventoryLeftPanel);

        filterLabel.setText("Filter");

        sortingLabel.setText("Sorting:");

        sortingComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "UPC","Name", "Categories", "Expiration Date" }));
        sortingComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                sortingComboBoxActionPerformed(evt);
            }
        });

        GroupLayout sortingPanelLayout = new GroupLayout(sortingPanel);
        sortingPanel.setLayout(sortingPanelLayout);
        sortingPanelLayout.setHorizontalGroup(
            sortingPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sortingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterLabel)
                .addGap(35, 35, 35)
                .addComponent(sortingLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortingComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sortingPanelLayout.setVerticalGroup(
            sortingPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sortingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortingPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(sortingLabel)
                    .addComponent(sortingComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdbc.GetConnection("default");
        inventoryTable.setModel(jdbc.GetModel());
        inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(175);
        inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(15);
        inventoryTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(5).setPreferredWidth(125);
        inventoryTable.getColumnModel().getColumn(6).setPreferredWidth(15);
     
        jScrollPane1.setViewportView(inventoryTable);

        GroupLayout inventoryRightPanelLayout = new GroupLayout(inventoryRightPanel);
        inventoryRightPanel.setLayout(inventoryRightPanelLayout);
        inventoryRightPanelLayout.setHorizontalGroup(
            inventoryRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(inventoryRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(sortingPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inventoryRightPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 900, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inventoryRightPanelLayout.setVerticalGroup(
            inventoryRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(inventoryRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sortingPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 298, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventorySplitPane.setRightComponent(inventoryRightPanel);

        inventoryTabPane.addTab("Inventory", inventorySplitPane);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryTabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryTabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addInventoryButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addInventoryButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_addInventoryButtonActionPerformed

    private void sortingComboBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sortingComboBoxActionPerformed
        String sort= (String)sortingComboBox.getSelectedItem();
    	if(sort.equals("UPC")){
            jdbc.GetConnection("default");
            inventoryTable.setModel(jdbc.GetModel());
            inventoryTable.repaint();
        }    	
        else if(sort.equals("Name")){
        	jdbc.GetConnection("Name");
        	inventoryTable.setModel(jdbc.GetModel());
        	inventoryTable.repaint();
        }else if (sort.equals("Categories")) {
        	jdbc.GetConnection("Categories"); 
        	inventoryTable.setModel(jdbc.GetModel());
        inventoryTable.repaint();
        }else if (sort.equals("Expiration Date")) {
        	jdbc.GetConnection("date"); 
        	inventoryTable.setModel(jdbc.GetModel());
        inventoryTable.repaint();
        }
        inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(175);
        inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(15);
        inventoryTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(5).setPreferredWidth(125);
        inventoryTable.getColumnModel().getColumn(6).setPreferredWidth(15);
      
    }//GEN-LAST:event_sortingComboBoxActionPerformed
 
    private void categoriesSelectionActionPerformed(java.awt.event.ActionEvent evt) {
        
        jdbc.GetConnection("default");
        if(bakingCB.isSelected())
        {
            jdbc.GetConnection("bakingCategory");
        }
        if(beveragesCB.isSelected()){
            jdbc.GetConnection("beverageCategory");
            
        }
        if(breadsBakeryCB.isSelected()){
            jdbc.GetConnection("breadsBCategory");
            
        }
        if(dairyRefCB.isSelected()){
            jdbc.GetConnection("dairyRCategory");
            
        }
        if(householdSCB.isSelected()){
            jdbc.GetConnection("housholdSCategory");
            
        }
        if(meatsPoultryCB.isSelected()){
            jdbc.GetConnection("meatsPCategory");
            
        }
        if(miscellaneousCB.isSelected()){
            jdbc.GetConnection("miscellaneousCategory");
            
        }
        if(pantryCB.isSelected()){
            jdbc.GetConnection("pantryCategory");
            
        }
        inventoryTable.setModel(jdbc.GetModel());
        inventoryTable.repaint();
        inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(175);
        inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(15);
        inventoryTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        inventoryTable.getColumnModel().getColumn(5).setPreferredWidth(125);
        inventoryTable.getColumnModel().getColumn(6).setPreferredWidth(15);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bakingCB;
    private javax.swing.JCheckBox beveragesCB;
    private javax.swing.JCheckBox breadsBakeryCB;
    private javax.swing.JCheckBox dairyRefCB;
    private javax.swing.JCheckBox householdSCB;
    private javax.swing.JCheckBox meatsPoultryCB;
    private javax.swing.JCheckBox miscellaneousCB;
    private javax.swing.JCheckBox pantryCB;
    // End of variables declaration//GEN-END:variables
}
